config/routes.rb
Rails.application.routes.draw do
  
  resources :regis do
    resources :charts
    resources :patients
    resources :filings
  end
  
  devise_for :users
  
  resources :users
  
  get 'overviews/chart_date'
  get 'overviews/chart_name'
  get 'overviews/patient_info'
  get 'overviews/patient_list'
  # get 'restore_points/patient_list_update'
  # get 'restore_points/patient_charts_update'
  # get 'restore_points/patient_info_update'
  get 'consent' => 'sites#consent'
  get 'insurance' => 'sites#insurance'
  
  root 'sites#home'
end

app/controllers/overviews_controller.rb
class OverviewsController < ApplicationController
  def patient_list
    @patient_list = Regi.order("last_name, first_name, init, dob").all
  end

  def patient_info
  end
  
  def chart_name
    @chart_name = Chart.all
  end

  def chart_date
    @chart_date = Chart.all
  end

end

app/helpers/overviews_helper.rb
module OverviewsHelper
end

app/views/overviews/chart_date.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>

  <h2 class="text-center">Patient Charts by Date as of <%= Time.now.in_time_zone("America/New_York").strftime("%Y-%m-%d %H:%M") %></h2>
  
  <button onclick="window.print()", class="btn btn-sm btn-outline-success ps-3 pe-3 rounded-pill" >Print This Page</button>

  <table class="table table-sm table-striped table-hover mt-1">
    <thead class="table-info">
      <tr>
        <th style="width:90px">Date</th>
        <th>Name</th>
        <th>Subjective</th>
        <th>Objective</th>
        <th>Assessment</th>
        <th>Plan</th>
      </tr>
    </thead>
    </tbody>
        <% @date = 0 %>
        <% Chart.joins(:regi).order("t_date DESC, last_name, first_name, init, dob").each do |chart| %>
            <tr style="height:15px">
            <% @date != chart.t_date ? show_date = chart.t_date : show_date = " " %>
            <td><%= show_date %></td> 
            <% @date = chart.t_date %>
            <% @prefix = Regi.find(id = chart.regi_id) %>
            <% show_name = @prefix.last_name + ", " + @prefix.first_name + " " + (@prefix.init? ? @prefix.init + "." : " ") %>
            <% regi_id = Regi.where(id: chart.regi_id).pluck(:id).to_sentence %>
            <td><%= link_to show_name, regi_charts_path(regi_id) %></td>
            <td><%= chart.subj %></td>
            <td><%= chart.obj %></td>
            <td><%= chart.assess %></td>
            <td><%= chart.plan %></td>
            </tr>
        <% end %>
    </tbody>
  </table>

<% end %>

app/views/overviews/chart_name.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>

  <h2 class="text-center">Patient Charts by Name as of <%= Time.now.in_time_zone("America/New_York").strftime("%Y-%m-%d %H:%M") %></h2>
  
  <button onclick="window.print()", class="btn btn-sm btn-outline-success ps-3 pe-3 rounded-pill" >Print This Page</button>

  <table class="table table-sm table-striped table-hover mt-1">
    <thead class="table-info">
      <tr>
        <th>Name</th>
        <th style="width:100px">Date Entered</th>
        <th>Subjective</th>
        <th>Objective</th>
        <th>Assessment</th>
        <th>Plan</th>
      </tr>
    </thead>
    </tbody>
      <% @name = 0 %>
      <% Chart.joins(:regi).order("last_name, first_name, init, dob, t_date DESC").each do |chart| %>
        <tr style="height:15px">
        <% @prefix = Regi.find(id=chart.regi_id) %>
        <% @name != chart.regi_id ? show_name = @prefix.last_name + ", " + @prefix.first_name + " " + @prefix.init : show_name = " " %>
        <% regi_id = Regi.where(id: chart.regi_id).pluck(:id).to_sentence %>
        <td><%= link_to show_name, regi_charts_path(regi_id) %></td>
        <% @name = chart.regi_id %>
        <td><%= link_to chart.t_date, regi_chart_path(chart.regi_id, chart) %></td>
        <td><%= chart.subj %></td>
        <td><%= chart.obj %></td>
        <td><%= chart.assess %></td>
        <td><%= chart.plan %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/overviews/patient_info.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  
  <h2 class="text-center">Patient Information as of <%= Time.now.in_time_zone("America/New_York").strftime("%Y-%m-%d %H:%M") %></h2>

  <button onclick="window.print()", class="btn btn-sm btn-outline-success ps-3 pe-3 rounded-pill" >Print This Page</button>

  <table class="table table-sm table-striped table-hover mt-1">
    <thead class="table-success">
    <tr style="height:13px">
        <th>Name</th>
        <th style="width:115px">Date Entered</th>
        <th>Contact Info</th>
        <th>Weight</th>
        <th>Complaints</th>
        <th>Onset/Pain</th>
        <th>PCP</th>
        <th>Health History</th>
        <th style="width:115px">Meds Taken</th>
      </tr>
    </thead>
    </tbody>
      <% @name = 0 %>
      <% Patient.joins(:regi).order("last_name, first_name, init, dob, v_date DESC").each do |patient| %>
        <tr style="height:15px">
        <td>
        <% @prefix = Regi.find(id=patient.regi_id) %>
        <% @name != patient.regi_id ? show_name = @prefix.last_name + ", " + @prefix.first_name + " " + @prefix.init : show_name = " " %>
        <%= link_to show_name, regi_patient_path(patient.regi_id, patient) %>
        </td>
          <td>
          <%= patient.v_date %>
          </td>
          <td>
            <%= patient.street %><%= ', ' if patient.street? %>
            <%= patient.city %>
            <%= patient.state %>
            <%= patient.zip %>
            <%= 'Cell:' if patient.cell? %><%= patient.cell %>
            <%= 'Home:' if patient.home? %><%= patient.home %>
            <%= 'Work:' if patient.work? %><%= patient.work %>
            <%= 'Email:' if patient.email? %><%= patient.email %>
          </td>
          <td><%= patient.weight %></td>
          <td>
            <%= '1.' if patient.com1? %>
            <%= patient.com1.strip %><%= '; 2.' if patient.com2? %>
            <%= patient.com2.strip %><%= '; 3.' if patient.com3? %>
            <%= patient.com3.strip %>
          </td>
          <td>
            <%= patient.d_onset %><%= '/Pain: ' if patient.pain_scale? %>
            <%= patient.pain_scale %>
          </td>
          <td><%= patient.pcp_name %></td>
          <td>
            <%= patient.di_list.to_sentence.gsub(/_/, ' ').gsub(/;/, '') %><%= ', ' if patient.o_dis? %>
            <%= patient.o_dis %><%= ', ' if patient.inj_surg? %>
            <%= patient.inj_surg %><%= ', Preg' if patient.preg == 'Yes' %>
          </td>
          <td><%= patient.med_taken %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/overviews/patient_list.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>

  <h2 class="text-center">Patient List as of <%= Time.now.in_time_zone("America/New_York").strftime("%Y-%m-%d %H:%M") %></h2>
  <p class="text-center"><button onclick="window.print()", class="btn btn-sm btn-outline-dark mb-3 ps-3 pe-3 rounded-pill">Print Entire Patient List ... </button></p>
  
  <table class="table table-sm table-striped table-hover mx-auto mt-1;" style="width: 45rem;">
    <thead class="table-primary">
      <tr style="height:15px">
        <th>Last Name</th>
        <th>First Name</th>
        <th>M. Init</th>
        <th>Gender</th>
        <th>Age</th>
        <th style="width:120px">Date of Birth</th>
      </tr>
    </thead>
  <% @patient_list.each do |regi| %>

    <tr>
      <td><%= link_to regi.last_name, regi_path(regi.id) %></td>
      <td><%= regi.first_name %></td>
      <td><%= regi.init? ? regi.init + "." : "" %></td>
      <td><%= regi.gender %></td>
      <td><%= regi.dob? ? ((Time.now.in_time_zone("America/New_York") - regi.dob.to_time) / 1.year.seconds).floor : " " %></td>
      <td><%= regi.dob %></td>                
    </tr>
    <% end %>
  </table>

<% end %>