config/routes.rb
Rails.application.routes.draw do
  
  resources :regis do
    resources :charts
    resources :patients
    resources :filings
  end
  
  devise_for :users
  
  resources :users
  
  get 'overviews/chart_date'
  get 'overviews/chart_name'
  get 'overviews/patient_info'
  get 'overviews/patient_list'
  # get 'restore_points/patient_list_update'
  # get 'restore_points/patient_charts_update'
  # get 'restore_points/patient_info_update'
  get 'consent' => 'sites#consent'
  get 'insurance' => 'sites#insurance'
  
  root 'sites#home'
end

app/models/filing.rb
class Filing < ApplicationRecord
  belongs_to :regi
  has_one_attached :image, dependent: :destroy
end

app/controllers/filings_controller.rb
class FilingsController < ApplicationController
  before_action :set_regi
  before_action :set_filing, only: [:show, :edit, :update, :destroy]

  # GET regis/1/filings
  def index
    @filings = @regi.filings
  end

  # GET regis/1/filings/1
  def show
  end

  # GET regis/1/filings/new
  def new
    @filing = @regi.filings.build
  end

  # GET regis/1/filings/1/edit
  def edit
  end

  # POST regis/1/filings
  def create
    @filing = @regi.filings.build(filing_params)

    if @filing.save
      redirect_to regi_filings_path(@regi,@filing), notice: 'Patient File created...'
    else
      render action: 'new'
    end
  end
  
  # PUT regis/1/filings/1
  def update
    if @filing.update(filing_params)
      redirect_to regi_filings_path(@regi,@filing), notice: 'Patient File changed...'
    else
      render action: 'edit'
    end
  end

  # DELETE regis/1/filings/1
  def destroy
    @filing.destroy

    redirect_to regi_filings_url(@regi)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regi
      @regi = Regi.find(params[:regi_id])
    end

    def set_filing
      @filing = @regi.filings.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def filing_params
      params.require(:filing).permit(:u_date, :title, :describe, :regi_id, :image)
    end
end

app/views/filings/_form.html.erb
<div 
  class="screen"
  style="background-image: url(<%= asset_path 'pine_trees.jpg' %> );">
  <div class="color-overlay d-flex justify-content-center mt-5 pt-5">
    
    <div class="card mt-3 mx-auto border-primary" style="width: 33rem;">
        <div class="card shadow border-dark">
          <div class="card-header">
            <h2 class="card-title text-center">Filing</h2>
            <h3><%= render 'layouts/identifier' %></h3>
          </div>
          <div class="card-body">
            <%= form_for([@filing.regi, @filing]) do |f| %>
              <% if @filing.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@filing.errors.count, "error") %> prohibited this filing from being saved:</h2>

                  <ul>
                  <% @filing.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field"><br>
                <%= f.file_field :image,  class:'form-control border-primary' %>
              </div><br>
              
              <div class="field">
                <b><%= f.label :describe, "File Description" %></b><br>
                <%= f.text_area :describe,  class:'form-control border-primary' %>
              </div>

              <div class="actions">
                <%= f.submit "Submit", class: "btn btn-sm btn-primary ps-3 pe-3 mt-3 rounded-pill" %>
                <%= link_to 'Return', regi_filings_path(@filing.regi), class: "btn btn-sm btn-success ps-3 pe-3 mt-3 rounded-pill" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/filings/edit.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render 'form' %>
<% end %>

app/views/filings/index.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>

<div 
  class="screen"
  style="background-image: url(<%= asset_path 'pine_trees.jpg' %> );">
  <div class="color-overlay d-flex justify-content-center">    
    <div class="card mt-3 mx-auto border-primary" style="width: 48rem;">
        <div class="card shadow border-dark">
          <div class="card-header">
            <h1 class="text-center">Patient Files</h1>
            <%= render 'layouts/identifier' %>
          </div>
          <div class="card-body">
            <%= link_to 'New Filing', new_regi_filing_path(params[:regi_id]), class: "btn btn-sm btn-outline-dark m-1 rounded-pill" %>
            <%= link_to 'Patient Record', regi_patients_path, class:"btn btn-sm btn-outline-primary m-1 rounded-pill" %>
            <%= link_to 'Patient Charts', regi_charts_path, class:"btn btn-sm btn-outline-info m-1 rounded-pill" %>
            <%= link_to 'Return', :back, class:"btn btn-sm btn-outline-secondary m-1 rounded-pill" %>

            <table class="table table-sm table-striped table-hover mt-1">
              <thead class="table-info">
                <tr>
                  <th>File</th>
                  <th>Description</th>
                  <th>Uploaded at</th>
                  <th style="width:220px"></th>
                </tr>
              </thead>
              <tbody>
                <% @regi.filings.order("created_at DESC").each do |filing| %>
                  <tr>
                    <td>
                      <% if filing.image.attached? && filing.image.image? %>
                        <%= image_tag filing.image, height: "25px" %>
                      <% else %>
                        <% 'PDF' %>
                        <%= image_tag (asset_path 'pdf-logo.webp'), height: "25px" %>
                        <%# <img src = '/railspro/reach/app/assets/images/pdf-logo.webp' > %>
                      <% end %>
                    </td>
                    <td><%= filing.describe %></td>
                    <td><%= filing.updated_at.in_time_zone("America/New_York").strftime("%Y-%m-%d, %H:%M") %></td>
                    <td>
                      <div class="btn-group" role="group">
                      <%= link_to 'View', filing.image, class: "btn btn-sm btn-success ms-2 me-2 ps-3 pe-3 rounded-pill" %>
                      <%= link_to 'Change', edit_regi_filing_path(@regi,filing), class: "btn btn-sm btn-warning ms-2 me-2 rounded-pill" %>
                      <%= button_to "Delete", [@regi,filing], method: :delete, class:"btn btn-sm btn-danger ms-2 me-2 rounded-pill", form: { data: { turbo_confirm: "Are you sure?" } } %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  </div>
</div>

<% end %>

app/views/filings/new.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render 'form' %>
<% end %>

app/views/filings/show.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render 'layouts/identifier' %>

  <table class="table table-sm table-striped table-hover mt-1">
    <thead class="table-info">
      <tr>
        <th>Uploaded on</th>
        <th>File Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr style="height:15px">
        <td><%= @filing.u_date %></td>
        <td><%= @filing.title %></td>
        <td><%= @filing.describe %></td>
      </tr>
    </tbody>
  </table>

  <div class="btn-group" role="group">
    <% if @filing.image.attached? %>
      <%= link_to 'View File', @filing.image, class: "btn btn-sm btn-success m-2 rounded-pill" %>
    <% end %>
    <%= link_to 'Change', edit_regi_filing_path(@filing.regi, @filing), class: "btn btn-sm btn-warning m-2 rounded-pill" %>
    <%= button_to "Delete", [@regi,@filing], method: :delete, class:"btn btn-sm btn-danger m-2 rounded-pill", form: { data: { turbo_confirm: "Are you sure?" } } %>
    <%= link_to 'Return', regi_filings_path(@filing.regi), class: "btn btn-sm btn-primary m-2 rounded-pill" %>
  </div>
<% end %>

app/views/filings/show_old.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render 'layouts/identifier' %>

  <table class="table table-sm table-striped table-hover mt-1">
    <thead class="table-info">
      <tr>
        <th>Uploaded on</th>
        <th>File Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr style="height:15px">
        <td><%= @filing.u_date %></td>
        <td><%= @filing.title %></td>
        <td><%= @filing.describe %></td>
      </tr>
    </tbody>
  </table>

  <div class="btn-group" role="group">
    <% if @filing.image.attached? %>
      <%= link_to 'View File', @filing.image, class: "btn btn-sm btn-success m-2 rounded-pill" %>
    <% end %>
    <%= link_to 'Change', edit_regi_filing_path(@filing.regi, @filing), class: "btn btn-sm btn-warning m-2 rounded-pill" %>
    <%= button_to "Delete", [@regi,@filing], method: :delete, class:"btn btn-sm btn-danger m-2 rounded-pill", form: { data: { turbo_confirm: "Are you sure?" } } %>
    <%= link_to 'Return', regi_filings_path(@filing.regi), class: "btn btn-sm btn-primary m-2 rounded-pill" %>
  </div>
<% end %>