config/routes.rb
Rails.application.routes.draw do
  
  resources :regis do
    resources :charts
    resources :patients
    resources :filings
  end
  
  devise_for :users
  
  resources :users
  
  get 'overviews/chart_date'
  get 'overviews/chart_name'
  get 'overviews/patient_info'
  get 'overviews/patient_list'
  # get 'restore_points/patient_list_update'
  # get 'restore_points/patient_charts_update'
  # get 'restore_points/patient_info_update'
  get 'consent' => 'sites#consent'
  get 'insurance' => 'sites#insurance'
  
  root 'sites#home'
end

app/models/regi.rb
class Regi < ApplicationRecord
  has_many :filings, dependent: :destroy
  has_many :patients, dependent: :destroy
  has_many :charts, dependent: :destroy

  GENDER_OPTIONS = [
    ['Select', ''],
    ['Male', 'Male'],
    ['Female', 'Female'],
    ['Other', 'Other']
  ]
end

app/controllers/regis_controller.rb
class RegisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_regi, only: %i[ show edit update destroy ]

  # GET /regis or /regis.json
  def index
    @q = Regi.order("last_name, first_name, init, dob").ransack(params[:q])
    @regis = @q.result(distinct: true)
  end

  # GET /regis/1 or /regis/1.json
  def show
  end

  # GET /regis/new
  def new
    @regi = Regi.new
  end

  # GET /regis/1/edit
  def edit
  end

  # POST /regis or /regis.json
  def create
    @regi = Regi.new(regi_params)
    if @regi.save
      redirect_to regis_path, notice: "New Patient Registered..."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /regis/1 or /regis/1.json
  def update
    if @regi.update regi_params
      redirect_to regis_path, notice: "Patient Registration updated..."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /regis/1 or /regis/1.json
  def destroy
    @regi.destroy
    redirect_to regis_path, notice: "Patient Registration, records and charts all deleted..." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regi
      @regi = Regi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def regi_params
      params.require(:regi).permit(:last_name, :first_name, :init, :gender, :dob)
    end
end

app/helpers/regis_helper.rb
module RegisHelper
end

app/views/regis/_display.html.erb
<div 
  class="screen"
  style="background-image: url(<%= asset_path 'pine_trees.jpg' %> );">
  <div class="color-overlay d-flex justify-content-center mt-5">    
    <div class="card mt-3 mx-auto border-primary" style="width: 33rem;">
      <img src="..." class="card-img-top" alt="">
      <div class="card-title bg-secondary">
        <h2 class="text-center text-white mt-3">
          Edit Patient Registration
        </h2>
      </div>
      <div class="card-body">
        <div class="card-text">
          <%= render "form", regi:@regi %>
        </div>
      </div>
    </div>
  </div>
</div>




app/views/regis/_form.html.erb
<%= form_with(model: regi) do |form| %>
  <% if regi.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(regi.errors.count, "error") %> prohibited this regi from being saved:</h2>

      <ul>
        <% regi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-1">
    <div class="col col-md-3 pt-1 mt-1">
      <b><%= form.label :last_name, "Last Name" %></b>
    </div>
    <div class="col col-md-9">
      <%= form.text_field :last_name, autofocus: true, class:"form-control form-control-sm border-primary" %>
    </div>
  </div>

  <div class="row mb-1">
    <div class="col col-md-3 pt-1 mt-1">
      <b><%= form.label :first_name, "First Name" %></b>
    </div>
    <div class="col col-md-9">
      <%= form.text_field :first_name, class:"form-control form-control-sm border-primary" %>
    </div>
  </div>

  <div class="row mb-1">
    <div class="col col-md-3 pt-1 mt-1">
      <b><%= form.label :init, "Middle Inital" %></b>
    </div>
    <div class="col col-md-9">
      <%= form.text_field :init, class:"form-control form-control-sm border-primary" %>
    </div>
  </div>

  <div class="row input-group mb-1">
    <div class="col col-md-3 pt-1 mt-1">
      <b><%= form.label :gender, "Gender" %></b>
    </div>
    <div class="col col-md-9">
      <%= form.select :gender, Regi::GENDER_OPTIONS, class:"form-control form-control-sm border-primary" %>
    </div>
  </div>
 
 <div class="row mb-1">
    <div class="col col-md-3 pt-1 mt-1">
     <b><%= form.label :dob, "Date of Birth" %></b>
    </div>
    <div class="col col-md-9">
      <%= form.date_field :dob, placeholder: "MM/DD/YYYY", class:"form-control form-control-sm border-primary" %>
    </div>
  </div>
  <div>
    <div class="btn-group" role="group"> 
      <%= form.submit "Submit", class: "btn btn-sm btn-primary m-2 rounded-pill" %>
<% end %>      
      <%= button_to "Delete", @regi, method: :delete, class:"btn btn-sm btn-danger m-2 rounded-pill" %>
      <%= link_to "Return", :back, class:"btn btn-sm btn-success m-2 rounded-pill" %>
    </div>
  </div>


app/views/regis/_regi.html.erb
<div id="<%= dom_id regi %>">
  <p>
    <strong>Last name:</strong>
    <%= regi.last_name %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= regi.first_name %>
  </p>

  <p>
    <strong>Init:</strong>
    <%= regi.init %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= regi.gender %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= regi.dob %>
  </p>

</div>

app/views/regis/_search.html.erb
<%= link_to "Search Patient", "#offcanvasExample", data: { bs_toggle: "offcanvas" }, area: { controls: "offcanvasExample" }, role: "button", class: "btn btn-sm btn-outline-primary rounded-pill" %>
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasExampleLabel">Search Patients Here</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <%= search_form_for @q do |f| %>
        <div class="form-group">
          <b><%= f.label :by_last_name_start, "By first letters of the Last Name", class: "form-label" %></b>
          <%= f.search_field :last_name_start, class:"form-control form-control-sm border-primary mb-3" %>
        </div>
        <div class="form-group">
          <b><%= f.label :by_last_name_or_first_name_cont, "By letters in the Last Name or First Name", class: "form-label" %></b>
          <%= f.search_field :last_name_or_first_name_cont, class:"form-control form-control-sm border-primary mb-3" %>
        </div>
        <div class="form-group">
          <b><%= f.label :by_first_name_cont, "By First Name", class: "form-label" %></b>
          <%= f.search_field :first_name_cont, class:"form-control form-control-sm border-primary mb-3" %>
        </div>
        <div class="form-group">
          <b><%= f.label :by_gender_start, "By Gender (Male/Female/Other)", class: "form-label" %></b>
          <%= f.search_field :gender_start, class:"form-control form-control-sm border-primary mb-3" %>
        </div>
        <div class="form-group">
          <%= f.submit "Submit", class: 'btn btn-sm btn-outline-dark rounded-pill' %>
        </div>
      <% end %>
    </div>
  </div>
<%= link_to "Reset", regis_path, class: "btn btn-sm btn-outline-info ps-3 pe-3 m-1 rounded-pill" %>

app/views/regis/edit.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render "display" %> 
<% end %>

app/views/regis/index.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>

<div 
  class="screen"
  style="background-image: url(<%= asset_path 'pine_trees.jpg' %> );">
  <div class="color-overlay d-flex justify-content-center">    
    <div class="card mt-3 mx-auto border-primary" style="width: 48rem;">
        <div class="card shadow border-dark">
          <div class="card-header">
            <h2 class="card-title text-center">List of Patients</h2>
          </div>
          <div class="card-body">

            <%= link_to "New Patient", new_regi_path, class: "btn btn-sm btn-outline-dark ps-3 pe-3 rounded-pill" %>
            <%= render 'search' %>
            <%# link_to "Print", print_path, class: "btn btn-sm btn-outline-success ps-3 pe-3 rounded-pill" %>
            <table class="table table-sm table-striped table-hover mx-auto mt-1">
              <thead class="table-primary">
                <tr>
                  <th>Last Name</th>
                  <th>First Name</th>
                  <th>M. Init</th>
                  <th>Gender</th>
                  <th>Age</th>
                  <th>Date of Birth</th>
                  <th style="width:220px"></th>
                </tr>
              </thead>
            <% @regis.each do |regi| %>

              <tr>
                <td><%= link_to regi.last_name, regi_path(regi.id) %></td>
                <td><%= regi.first_name %></td>
                <td><%= regi.init? ? regi.init + "." : "" %></td>
                <td><%= regi.gender %></td>
                <td><%= regi.dob? ? ((Time.now.in_time_zone("America/New_York") - regi.dob.to_time) / 1.year.seconds).floor : " " %></td>
                <td><%= regi.dob %></td>                
                <td>
                <%= link_to 'Records', regi_patients_path(regi.id), class: "btn btn-outline-primary btn-sm rounded-pill" %>
                <%= link_to 'Charts', regi_charts_path(regi.id), class: "btn btn-outline-info btn-sm rounded-pill" %>
                <%= link_to 'Files', regi_filings_path(regi.id), class: "btn btn-outline-success btn-sm ps-3 pe-3 rounded-pill" %>
                </td>
              </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
  </div>
</div>

<% end %>

app/views/regis/new.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render "display", regi:@regi %>
<% end %>

app/views/regis/show.html.erb
<% if (current_user && current_user.Manager?) || (current_user && current_user.Admin?) %>
  <%= render "display" %>  
<% end %>