config/routes.rb
Rails.application.routes.draw do
  
  resources :regis do
    resources :charts
    resources :patients
    resources :filings
  end
  
  devise_for :users
  
  resources :users
  
  get 'overviews/chart_date'
  get 'overviews/chart_name'
  get 'overviews/patient_info'
  get 'overviews/patient_list'
  # get 'restore_points/patient_list_update'
  # get 'restore_points/patient_charts_update'
  # get 'restore_points/patient_info_update'
  get 'consent' => 'sites#consent'
  get 'insurance' => 'sites#insurance'
  
  root 'sites#home'
end

app/views/layouts/_alert.html.erb
<div id="flash-messages">
  <% flash.each do |name, msg| %>
    <div class="alert pt-1 pb-0 alert-<%= name == 'notice' ? 'warning' : 'danger'%> alert-dismissible fade show d-flex justify-center-between" role="alert">
      <p class="pb-0"><strong><%= msg %></strong></p>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<div>

app/views/layouts/_identifier.html.erb
<% @age = @regi.dob? ? ((Time.now.in_time_zone("America/New_York") - @regi.dob.to_time) / 1.year.seconds).floor : "<No data>" %>

<% @gender = @regi.gender? ? @regi.gender : "<No gender data>" %>

<h4 class="text-center"><%= @regi.last_name %>, <%= @regi.first_name %> <%= @regi.init %><%= '.' if @regi.init? %> | Age: <%= @age %> | <%= @gender %> </h4>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark fixed-top bg-primary pt-1 pb-1" id="mainNav">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class:"navbar-brand fw-bold" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# if current_user %>
          <%# link_to "Insurance", "insurance_path", class:"nav-link text-white bg-success rounded-pill" %>
          <%# link_to "Consent Form", consent_path, class:"nav-link text-white bg-success rounded-pill" %>
        <%# end %>

        <% if current_user %>
          <li class="nav-item">
            <%# link_to "|log out|", reset_path, class:"nav-link active" %>
            <%# link_to "log out", destroy_user_session_path, class:"nav-link text-dark fw-bold bg-info rounded-pill border border-dark border-2", method: :delete %>
            <%= button_to("Log out", destroy_user_session_path, class:"nav-link text-dark fw-bold bg-info rounded-pill border border-dark border-2", method: :delete, data: { turbo_method: :delete }) %>
            <%# link_to "|Log out|", destroy_user_session_path, class:"nav-link active", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class:"nav-link text-dark fw-bold bg-info rounded-pill border border-dark border-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Scheduler", "https://calendar.google.com/calendar", class:"nav-link text-dark ms-1 fw-bold bg-info rounded-pill border border-dark border-2" %>
          </li>
          <li class="nav-item">
            <%# link_to "Sign up", new_user_registration_path, class:"nav-link text-dark fw-bold bg-info rounded-pill border border-dark border-2" %>
          </li>
        <% end %>  

        <% if (current_user && current_user.Admin?) || (current_user && current_user.Manager?) %>

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle dropdown-toggle-split nav-link text-dark ms-1 fw-bold bg-info rounded-pill border border-dark border-2" id="navbarDropdownMenuLink" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Overview
          </button>
          <ul class="dropdown-menu dropdown-menu-dark" id="navbarDropdownMenuLink">
            <li><%= link_to "Patient List", overviews_patient_list_path, class: "dropdown-item" %></li>
            <li><%= link_to "Patient Info", overviews_patient_info_path, class: "dropdown-item" %></li>
            <li><%= link_to "Charts by Name", overviews_chart_name_path, class: "dropdown-item" %></li>
            <li><%= link_to "Charts by Date", overviews_chart_date_path, class: "dropdown-item" %></li>
          </ul>
        </div>

          <li class="nav-item">
            <%= link_to "Patients", regis_path, class:"nav-link text-dark ms-1 fw-bold bg-info rounded-pill border border-dark border-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Scheduler", "https://calendar.google.com/calendar", class:"nav-link text-dark ms-1 fw-bold bg-info rounded-pill border border-dark border-2" %>
          </li>
        <% end %>

        <% if current_user && current_user.Admin? %>

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle dropdown-toggle-split nav-link text-dark ms-1 fw-bold bg-info rounded-pill border border-dark border-2" id="navbarDropdownMenuLink" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin Portal
          </button>
          <ul class="dropdown-menu dropdown-menu-dark" id="navbarDropdownMenuLink">
            <li><%= link_to "Users and usages", users_path, class: "dropdown-item" %></li>
            <li><%# link_to "Patient List Update", restore_points_patient_list_update_path, class: "dropdown-item"</li> %>
            <li><%# link_to "Patient Info Update", restore_points_patient_info_update_path, class: "dropdown-item" %></li>
            <li><%# link_to "Patient Charts Update", restore_points_patient_charts_update_path, class: "dropdown-item" %></li>
          </ul>
        </div>
          <li class="nav-item">
            <%# link_to "Sign up", new_user_registration_path, class:"nav-link text-dark fw-bold bg-info rounded-pill" %>
          </li>
        <% end %>
      </ul>

      <li class="d-flex">
        <% if current_user && current_user.Admin? %>
          <p class="text-dark fw-bold bg-info mt-1 mb-1 p-3 pt-1 pb-1 rounded-pill border border-dark border-2"><%= current_user.email %> : <%= current_user.role %></p>
        <% end %>
      </li>
    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"%>
    <%# javascript_importmap_tags %>

    <title>BinPro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container-fluid mt-5"><br>
      <div class="text-end">
        <%= image_tag "title_1.png" %><br>
      </div>
    <%= render "layouts/alert" %>
      <div class="float-center">
      <%= yield %>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  </body>
</html>